# Generated by Django 5.1.4 on 2025-02-27 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_progress'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Progress',
        ),
    ]
